spring:
  application:
    name: project_3

  datasource:
    url: jdbc:mariadb://localhost:3306/thanh?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # C?u hï¿½nh ??n gi?n cho Spring Security
  security:
    oauth2:
      resourceserver: {}

# Server
server:
  port: 8082

# Logging
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

minio:
  url: http://103.118.29.245:9000
  access-key: minoadmin
  secret-key: minioadmin123
  bucket: thanhnguyen
