spring:
  application:
    name: project_3

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mariadb://localhost:3307/social_media
    username: social
    password: social
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  security:
    oauth2:
      resourceserver: {}

# Server
server:
  port: 8082

# Logging
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

minio:
  url: http://103.118.29.245:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket:
    avatar: thanhnguyen
    media: thanhnguyen

